# Generated by Django 5.1.1 on 2024-09-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plagehoraire',
            name='actions',
            field=models.CharField(choices=[('allumer', 'Allumer'), ('eteindre', 'Éteindre')], default='allumer', max_length=8),
            preserve_default=False,
        ),
    ]
