# Generated by Django 5.1.1 on 2024-10-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0002_plagehoraire_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plagehoraire',
            name='actions',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='plagehoraire',
            name='led',
            field=models.CharField(choices=[('LED1', 'LED 1'), ('LED2', 'LED 2'), ('ALL', 'Toutes les LEDs')], max_length=10),
        ),
        migrations.AlterField(
            model_name='plagehoraire',
            name='nom_plage',
            field=models.CharField(max_length=100),
        ),
    ]
