# Generated by Django 5.1.2 on 2024-10-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0003_alter_plagehoraire_actions_alter_plagehoraire_led_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telephone', models.CharField(max_length=10)),
                ('serveur_smtp', models.CharField(max_length=25)),
                ('port_smtp', models.IntegerField()),
                ('email_expediteur', models.EmailField(max_length=254)),
                ('mot_de_passe', models.CharField(max_length=50)),
                ('email_destinataire', models.EmailField(max_length=254)),
            ],
        ),
    ]
